### ISSUE TITLE
init-rapport

### ISSUE THREAD

**Issue by Yasmine-daifane** [cnmh/besoin#98]
# Init rapport

## Travail à faire

- Élaboration d'un rapport sans contenu avec les pages et leurs titres

## Livrable 

- Backlog /sous-tâche/*
- docs/* : je vais modifier tous les fichier dans cette repertoire
- docs/rapport.html
- rapport.md
- index.md
- Readme.json : je vais ajouter seleument le lien de rapport
- Readme.md  : je vais ajouter seleument le lien de rapport

**Comment by husseinbouik** [comment]
la description de la tâche n'est pas valide

**Comment by husseinbouik** [comment]
- le résultat n'est pas conforme au livrables dans la description de l'issue
