### ISSUE TITLE
init-presentation

### ISSUE THREAD

**Issue by Yasmine-daifane** [cnmh/besoin#99]
# Init présentation

## Travail à faire 
Création d'une présentation sans contenu, mais avec les titres des diapositives
## Livrable 
- docs/* : je vais modifier tous les fichier dans cette repertoire
- docs/présentation.html
- presentation.md
- index.md
- Readme.json : je vais ajouter seleument le lien de presentation
- Readme.md  : je vais ajouter seleument le lien de presentation

**Comment by husseinbouik** [comment]
la description de la tâche n'est pas valide
